title: Lindsey Scott # your name (or website title) here
logo: "/images/IMAG0240_edited6558748888.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
The most athletic, self-taught Power BI Developer one never knew of. I make dashboards. Sometimes they help. Sometimes they inspire.  Sometimes they just remind people someone is paying attention.
<br><br>
I don’t build dashboards to find insights.
<br><br>
Most of the time, I do not even know what an insight is. What I do know - people don’t need more data. They need someone to make them feel like the data was made for them.
<br><br>
This blog won’t teach you how to become a Power BI guru. It’ll just show you how I try to make sense of the mess—and why I still care about doing it well.
<br><br>
Blog Posts To Come-  maybe a Power BI trick. Maybe just a rant about buttons.
<br><br>
Let’s see how this goes.
<br><br>
<a href="https://www.linkedin.com/in/lindsey-scott-ab77b920">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
